version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: homework

  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: incorrect
    
  dotnet_minio:
    image: minio/minio:latest
    
  dotnet_mongodb:
    image: mongo:latest
    
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    ports:
      - "5065:80"
    build:
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    depends_on:
      - dotnet_postgres
      - dotnet_mailing
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=dotnet_postgres;Username=postgres;Password=postgres;Database=homework
      RabbitMQ__Hostname: dotnet_rabbitmq
      RabbitMQ__Username: username
      RabbitMQ__Password: incorrect

  dotnet_mailing:
    build:
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    environment:
      EmailConfig__Email: admin@example.com
      EmailConfig__Port: 443
      EmailConfig__Host: example.com
      EmailConfig__Password: adminadmin
      RabbitMQ__Hostname: dotnet_rabbitmq
      RabbitMQ__Username: username
      RabbitMQ__Password: incorrect
    depends_on:
      - dotnet_rabbitmq
    
  dotnet_storage:
    image: dotnet-web