version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: homework

  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    
  dotnet_minio:
    image: minio/minio:latest
    
  dotnet_mongodb:
    image: mongo:latest
    
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    image: dotnet-web
    build:
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    depends_on:
      - dotnet_postgres
    environment:
      ConnectionStrings__Default: Host=dotnet_postgres;Username=postgres;Password=postgres;Database=homework

  dotnet_mailing:
    image: dotnet-web
    
  dotnet_storage:
    image: dotnet-web